name: 'reconfigured'
version: '0.1.0'
config-version: 2

model-paths: []
analysis-paths: []
test-paths: []
seed-paths: []
macro-paths: ["macros"]
snapshot-paths: []

clean-targets:
  - "target"
  - "dbt_packages"
